### PR TITLE
Fix typos in README

### PR DESCRIPTION
**Pull request by lachlanjc**
:wave: Thanks for this incredible project! Spotted some typos while getting started with the README.

### CODE REVIEW

**Comment by bbohlender** [comment]
@lachlanjc thanks for the PR, can you make the same changes to the docs page
https://github.com/pmndrs/uikit/blob/main/docs/getting-started/introduction.md

**Comment by lachlanjc** [comment]
Done!

**Comment by bbohlender** [comment]
@lachlanjc I am sorry to be picky but now the README and the introduction are inconsistent, you made a few changes to the introduction that is not in the README

**Comment by bbohlender** [comment]
Thanks @lachlanjc

**Pull request merged**
