### PR TITLE
Fix component ref types and docs

### PR DESCRIPTION
**Pull request by Ledzz**

### CODE REVIEW

**Comment by Ledzz** [comment]
Closes #66

**Comment by bbohlender** [comment]
Thanks for the PR, I just checked the typing again and I think the correct typing would be
`RootProperties & RefAttributes<ComponentInternals<BaseRootProperties & EventHandlers>>) => ReactNode` for root where `BaseRootProperties` are the `RootProperties` form `uikit/internals`
and same for text (`TextProperties & RefAttributes<ComponentInternals<BaseTextProperties & EventHandlers>>) => ReactNode`) etc.
Sorry for not noticing earlier. Could you make these changes to all react components? :) 🙏🏼

**Comment by Ledzz** [comment]
yes sure, will do!

**Comment by Ledzz** [comment]
Do you think I should add EventHandlers there? As I understand ComponentInternals's is generic so we can type setStyle correctly. Or should it be used for getComputedProperty also?

**Comment by bbohlender** [comment]
Sorry for the delay.
Yes, it should be used for getComputedProperty also :)
setStyle, getStyle, and getComputedProperty should all use the same type since setStyle writes the signal that getStyle reads, and getComputedProperty also reads the same signal combined with other values from properties, defaults, and conditionals.

**Comment by Ledzz** [comment]
@bbohlender Could you please help? I have a typing error after my last edits, but I don't know how to locate it. Also could you please double check video.tsx typings?

**Comment by bbohlender** [comment]
I'll check it out locally in a sec.
Regarding the typing in video.tsx you forgot the `ComponentInternals`:
```
export type VideoInternals = ComponentInternals<BaseVideoContainerProperties &
  EventHandlers> & {
    element: HTMLVideoElement
  }
```

**Comment by bbohlender** [comment]
I pushed a fix :)

**Comment by Ledzz** [comment]
aw thanks, I guess it's ready then :)

**Comment by bbohlender** [comment]
> I'll check it out locally in a sec. Regarding the typing in video.tsx you forgot the `ComponentInternals`:
> 
> ```
> export type VideoInternals = ComponentInternals<BaseVideoContainerProperties &
>   EventHandlers> & {
>     element: HTMLVideoElement
>   }
> ```

Should I fix that myself (its no problem, have the branch checked out anyways)

**Comment by Ledzz** [comment]
no, I'll fix it soon, sorry, missed this message

**Comment by Ledzz** [comment]
no, I guess I need your help😬 Don't understand the types in video(

**Comment by bbohlender** [comment]
yeah it was a little more complex, pushed it myself, hope its okay. If you're fine with it, then I'll merge it soon :)

```
ComponentInternals<Omit<ImageProperties, 'src'> & EventHandlers> & {
  element: HTMLVideoElement
}
```

**Comment by Ledzz** [comment]
yes, sure :)

**Pull request merged**
