### PR TITLE
Basic Video Element Similar to Ima

### PR DESCRIPTION
**Pull request by Deamoner**

### CODE REVIEW

**Comment by bbohlender** [comment]
Hey @Deamoner thanks for getting this started, I've continued your efforts in #40 
Feel free to ask why I implemented things the way I did :)

**Comment by Pipe-Runner** [comment]
@bbohlender This has not been released yet, right? The code changes seem very recent and the documentation website does not mention any video element.

**Comment by bbohlender** [comment]
@Pipe-Runner it is released
the docs don't update directly so they can shortly be outdated
the source of the docs concerning the VideoContainer is here: https://github.com/pmndrs/uikit/blob/main/docs/getting-started/components-and-properties.md#videocontainer

**Comment by Pipe-Runner** [comment]
@bbohlender Thanks. Was wonder if the documentation should use `VideoContainer` in the example code. Am I missing something?

image

**Comment by bbohlender** [comment]
@Pipe-Runner totally right, will fix

**Pull request closed without merging**
